### ISSUE TITLE
Add pure-cdb to Stackage.

### ISSUE THREAD

**Issue by jship** [bosu/pure-cdb#3]
It would be helpful if pure-cdb was available on Stackage.  This looks to be a prerequisite for getting hscope on Stackage.

Are you interested in this?  I can set up Stackage's build-constraints.yml if you'd like.

**Comment by bosu** [comment]
Yes, am interested and will happily merge pull requests regarding this.

Thanks.

**Comment by jship** [comment]
This package looks to already be Stackage-ready.  I submitted PR #4 to improve the project's build compatibility and testability.

Getting projects on Stackage involves updating Stackage's [build-constraints.yaml](https://github.com/fpco/stackage/edit/master/build-constraints.yaml) and submitting a PR for it.  Updating the file consists of adding the maintainer name, email, and package name.

I'd be fine with putting myself on as the maintainer if you'd prefer.  In that case, I would clearly mark your package as included on your behalf.  Otherwise, you would have to  edit that file with your info.

Let me know what you think.

**Comment by bosu** [comment]
Merged and uploaded, thanks!

**Comment by jship** [comment]
Just a heads up: This is officially in Stackage starting with the [2016-01-22 nightly](https://www.stackage.org/nightly-2016-01-22).

I added the package on your behalf in Stackage's [build-constraints.yaml](https://github.com/fpco/stackage/edit/master/build-constraints.yaml) file.  Feel free to update this file to replace my name with yours if you'd prefer to be the Stackage maintainer.  I have clearly marked that I am not the original author of the package.

Thanks!

**Comment by bosu** [comment]
Hi Jason,

Thanks for doing that! I am certainly fine with you being Stackage
maintainer.

Thanks,
Boris.
